-- Nhật ký VT hỏng / cần sửa chữa (lưu vĩnh viễn để tải xuống)

CREATE TABLE `asset_broken_logs` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`createdAt` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`updatedAt` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`event_type` text NOT NULL,
	`source_type` text DEFAULT 'OTHER' NOT NULL,
	`source_id` integer,
	`proposal_id` integer,
	`repair_request_id` integer,
	`room_asset_id` integer,
	`source_asset_id` integer,
	`asset_code` text,
	`original_code` text,
	`asset_name` text NOT NULL,
	`category` text,
	`quantity` integer DEFAULT 1 NOT NULL,
	`original_grade` integer,
	`grade_after` integer,
	`status_after` text,
	`room_id` integer,
	`room_code` text,
	`room_name` text,
	`floor_name` text,
	`building_code` text,
	`building_name` text,
	`unit_name` text,
	`nganh_code` text,
	`reason` text,
	`result_note` text,
	`performer` text,
	`event_at` text NOT NULL,
	`actor_user_id` integer,
	`actor_username` text,
	`actor_display_name` text
);
