services:
    app:
        depends_on:
            nsqd:
                condition: service_healthy
            nsqlookupd:
                condition: service_healthy
        image: quanlyhocvien-cdhc2:test
        ports:
            - '8080:8080'
        environment:
            - PORT=8080
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8080/healthz']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
        networks:
            - nsq-network
            - cron-network
            - app-network
    web:
        depends_on:
            app:
                condition: service_healthy
        image: quanlyhocvien-cdhc2:test-web
        ports:
            - '3005:80'
        restart: unless-stopped
        networks:
            - app-network
    cron-scheduler:
        image: alpine:latest
        environment:
            - TZ=Asia/Ho_Chi_Minh
            - APP_URL=http://app:8080
        volumes:
            - ./cron/scripts:/scripts:ro
            - ./cron/logs:/var/log/cron:rw
        depends_on:
            app:
                condition: service_healthy
        restart: unless-stopped
        networks:
            - cron-network
        command: >
            sh -c "


              apk add --no-cache curl tzdata &&
              cp /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime &&
              echo 'Asia/Ho_Chi_Minh' > /etc/timezone &&

              echo '# Student Birthday Notifications' > /etc/crontabs/root &&
              # echo '0 0 * * 1 /scripts/weekly_birthday.sh >> /var/log/cron/weekly.log 2>&1' >> /etc/crontabs/root &&
              echo '30 * * * * /scripts/weekly_birthday.sh >> /var/log/cron/weekly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 1 * * /scripts/monthly_birthday.sh >> /var/log/cron/monthly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 1 */3 * /scripts/quarterly_birthday.sh >> /var/log/cron/quarterly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 * * 1 /scripts/weekly_cpv_official.sh >> /var/log/cron/weekly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 1 * * /scripts/monthly_cpv_official.sh >> /var/log/cron/monthly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 1 */3 * /scripts/quarterly_cpv_official.sh >> /var/log/cron/quarterly.log 2>&1' >> /etc/crontabs/root &&

              echo 'Current time after timezone setup:' &&
              date &&
              echo 'Cron jobs installed:' &&
              cat /etc/crontabs/root &&
              crond -f -l 2
            "

    # NSQ Lookup Daemon - service discovery for NSQ
    nsqlookupd:
        image: nsqio/nsq:v1.2.1
        command: /nsqlookupd
        ports:
            - '4160:4160' # TCP port for nsqd
            - '4161:4161' # HTTP port for admin interface
        networks:
            - nsq-network
        restart: unless-stopped
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:4161/ping'
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
    # NSQ Daemon - handles message queuing
    nsqd:
        image: nsqio/nsq:v1.2.1
        command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
        depends_on:
            nsqlookupd:
                condition: service_healthy
        ports:
            - '4150:4150' # TCP port for producers/consumers
            - '4151:4151' # HTTP port for admin interface
        networks:
            - nsq-network
        restart: unless-stopped
        volumes:
            - nsq-data:/data
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:4151/ping'
                ]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 15s
    # NSQ Admin UI (optional but recommended for monitoring)
    nsqadmin:
        image: nsqio/nsq:v1.2.1
        command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
        depends_on:
            nsqlookupd:
                condition: service_healthy
            nsqd:
                condition: service_healthy
        ports:
            - '4171:4171' # Web UI port
        networks:
            - nsq-network
        restart: unless-stopped
        healthcheck:
            test:
                [
                    'CMD',
                    'wget',
                    '--no-verbose',
                    '--tries=1',
                    '--spider',
                    'http://localhost:4171/ping'
                ]
            interval: 15s
            timeout: 5s
            retries: 3
            start_period: 20s
networks:
    app-network:
        driver: bridge
    cron-network:
        driver: bridge
    nsq-network:
        driver: bridge
volumes:
    cron_logs:
        driver: local
    nsq-data:
