export interface Student {
        TT: number;
        'Họ và tên': string;
        'Năm sinh': number;
        'Quê quán': string;
        'Hộ khẩu thường trú': string;
        CB: string;
        CV: string;
        'Đơn vị cũ': string;
        'Dân tộc': string;
        'Tôn giáo': string;
        'Nhập ngũ': number;
        Đoàn: number;
        Đảng: number | null;
        'Chính thức': number | null;
        'Số thẻ Đảng (Nếu có)': string | null;
        'Trình độ học vấn': string;
        'Tên trường': string | null;
        'Ngành nghề đào tạo': string | null;
        'Chức vụ công tác đơn vị cũ - chuyên ngành': string;
        'Diện chính sách': string | null;
        'Năng khiếu': string | null;
        'Sở đoản': string | null;
        Bố: string;
        'Năm sinh bố': number;
        'Nghề nghiệp bố': string;
        'SĐT Bố': number;
        Mẹ: string;
        'Năm sinh mẹ': number;
        'Nghề nghiệp mẹ': string;
        'SĐT mẹ': number;
        Vợ: string | null;
        'Năm sinh vợ': number | null;
        'Nghề nghiệp vợ': string | null;
        'SĐT vợ': number | null;
        'Con _ Năm sinh': string | null;
        'Gia đình có mấy thành viên': number | null;
        'Là con thứ mấy': number;
        'Sơ lược hoàn cảnh gia đình': string | null;
        'Thành tích': string | null;
        'Kỷ luật': string | null;
        Lớp: string;
}
