services:
    app:
        image: quanlyhocvien-cdhc2:test-cron
        ports:
            - '8080:8080'
        environment:
            - PORT=8080
        restart: unless-stopped
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8080/healthz']
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
    cron-scheduler:
        image: alpine:latest
        environment:
            - TZ=Asia/Ho_Chi_Minh
            - APP_URL=http://app:8080
        volumes:
            - ./cron/scripts:/scripts:ro
            - ./cron/logs:/var/log/cron:rw
        depends_on:
            app:
                condition: service_healthy
        restart: unless-stopped
        command: >
            sh -c "


              apk add --no-cache curl tzdata &&
              cp /usr/share/zoneinfo/Asia/Ho_Chi_Minh /etc/localtime &&
              echo 'Asia/Ho_Chi_Minh' > /etc/timezone &&

              echo '# Student Birthday Notifications' > /etc/crontabs/root &&
              echo '0 0 * * 4 /scripts/weekly_birthday.sh >> /var/log/cron/weekly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 1 * * /scripts/monthly_birthday.sh >> /var/log/cron/monthly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 1 */3 * /scripts/quarterly_birthday.sh >> /var/log/cron/quarterly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 * * 4 /scripts/weekly_cpv_official.sh >> /var/log/cron/weekly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 1 * * /scripts/monthly_cpv_official.sh >> /var/log/cron/monthly.log 2>&1' >> /etc/crontabs/root &&
              echo '0 0 1 */3 * /scripts/quarterly_cpv_official.sh >> /var/log/cron/quarterly.log 2>&1' >> /etc/crontabs/root &&

              echo 'Current time after timezone setup:' &&
              date &&
              echo 'Cron jobs installed:' &&
              cat /etc/crontabs/root &&
              crond -f -l 2
            "

volumes:
    cron_logs:
        driver: local
